sudo: required

services:
  - docker

matrix:
  include:
    - env: IMAGE=docker-git-compose
    - env: IMAGE=yapf

script:
  - docker build -f ${IMAGE}.Dockerfile -t albertzhuang/${IMAGE}:$TRAVIS_COMMIT -t albertzhuang/${IMAGE}:latest .
  
after_success:
  - docker login -u="$DOCKER_USER" -p="$DOCKER_PASS"
  - docker push albertzhuang/${IMAGE}
