sudo: required

services:
  - docker

script:
  - docker build -t albertzhuang/docker-git-compose:$TRAVIS_COMMIT -t albertzhuang/docker-git-compose:latest .
  
after_success:
  - docker login -u="$DOCKER_USER" -p="$DOCKER_PASS"
  - docker push albertzhuang/docker-git-compose
